      INTEGER FUNCTION FRMATI(IWIDTH)
C
C  THIS FUNCTION COMPUTES THE WIDTH, W, IN THE FORMAT SPECIFICATION
C  FOR INTEGER VARIABLES - IW
C
C  FRMATI RETURNS, AS THE VALUE FOR W, THE NUMBER OF CHARACTER
C  POSITIONS NEEDED FOR WRITING OUT THE LARGEST INTEGER PLUS
C  ONE POSITION FOR THE SIGN.
C  IWIDTH IS SET TO THE SAME VALUE.
C
C  I1MACH(7) IS THE BASE, A, FOR INTEGER REPRESENTATION IN THE MACHINE.
C  I1MACH(8) IS THE (MAXIMUM) NUMBER OF BASE A DIGITS.
C
      INTEGER I1MACH, ICEIL, IWIDTH
C
      FRMATI = ICEIL( ALOG10(FLOAT(I1MACH(7)))*FLOAT(I1MACH(8)) ) + 1
      IWIDTH = FRMATI
C
      RETURN
      END
