      SUBROUTINE N5ERR(MESSG, NMESSG, NERR, IOPT)
      INTEGER MESSG(1), NMESSG, NERR, IOPT
C  N5ERR IS A PROCEDURE USED TO REDEFINE AN ERROR STATE.
      CALL ERROFF
      CALL SETERR(MESSG, NMESSG, NERR, IOPT)
      RETURN
      END
