      SUBROUTINE  CCOPY(N,CX,INCX,CY,INCY)
C
C     COPIES A VECTOR, X, TO A VECTOR, Y.
C     JACK DONGARRA, LINPACK, 3/11/78.
C
C     ADAPTED TO PORT 3 BY PHYL FOX, 11/8/83
C
      COMPLEX CX(1),CY(1)
      INTEGER I,INCX,INCY,IX,IY,N
C
      IF(N.EQ.0)RETURN
C/6S
      IF(N .LT. 0) CALL SETERR(12HCCOPY-N.LT.0, 12, 1, 2)
      IF(INCY .EQ. 0) CALL SETERR(15HCCOPY-INCY.EQ.0, 15, 3, 2)
C/7S
C     IF(N .LT. 0) CALL SETERR('CCOPY-N.LT.0', 12, 1, 2)
C     IF(INCY .EQ. 0) CALL SETERR('CCOPY-INCY.EQ.0', 15, 3, 2)
C/
C
      IF(INCX.EQ.1.AND.INCY.EQ.1)GO TO 20
C
C        CODE FOR UNEQUAL INCREMENTS OR EQUAL INCREMENTS
C          NOT EQUAL TO 1
C
      IX = 1
      IY = 1
      IF(INCX.LT.0)IX = (-N+1)*INCX + 1
      IF(INCY.LT.0)IY = (-N+1)*INCY + 1
      DO 10 I = 1,N
        CY(IY) = CX(IX)
        IX = IX + INCX
        IY = IY + INCY
   10 CONTINUE
      RETURN
C
C        CODE FOR BOTH INCREMENTS EQUAL TO 1
C
   20 DO 30 I = 1,N
        CY(I) = CX(I)
   30 CONTINUE
      RETURN
      END
