      COMPLEX FUNCTION  CDOTU(N,DX,INCX,DY,INCY)
C THIS FUNCTION COMPUTES THE DOT PRODUCT OF X AND Y
C ONLY EVERY INCXTH COMPONENT OF X AND EVERY INCYTH
C COMPONENT OF Y IS CONSIDERED
C
      COMPLEX DX(INCX,1),DY(INCY,1)
       CDOTU = CMPLX(0.0,0.0)
       IF (N.EQ.0) RETURN
C/6S
      IF (N.LT.0) CALL SETERR(13H CDOTU-N.LT.0,13,1,2)
      IF(INCX.LT.1) CALL SETERR(16H CDOTU-INCX.LT.1,16,2,2)
      IF(INCY.LT.1) CALL SETERR(16H CDOTU-INCY.LT.1,16,3,2)
C/7S
C     IF (N.LT.0) CALL SETERR(' CDOTU-N.LT.0',13,1,2)
C     IF(INCX.LT.1) CALL SETERR(' CDOTU-INCX.LT.1',16,2,2)
C     IF(INCY.LT.1) CALL SETERR(' CDOTU-INCY.LT.1',16,3,2)
C/
      DO 10 I = 1,N
         CDOTU =  CDOTU+ DX(1,I)*DY(1,I)
   10 CONTINUE
      RETURN
      END
