        DOUBLE PRECISION FUNCTION DASUM(N,X,INCX)
C
C THIS FUNCTION RETURNS THE SUM OF THE ABSOLUTE VALUES
C OF THE COMPONENTS OF X. ONLY EVERY INCXTH COMPONENT
C OF X IS CONSIDERED
       DOUBLE PRECISION X(INCX,1)
       DASUM=0.D0
       IF(N.EQ.0) RETURN
C/6S
       IF (N.LT.0) CALL SETERR(12HDASUM-N.LT.0,12,1,2)
       IF(INCX.LT.1) CALL SETERR(15HDASUM-INCX.LT.1,15,2,2)
C/7S
C      IF (N.LT.0) CALL SETERR('DASUM-N.LT.0',12,1,2)
C      IF(INCX.LT.1) CALL SETERR('DASUM-INCX.LT.1',15,2,2)
C/
       DO 10 I=1,N
          DASUM=DASUM+DABS(X(1,I))
 10    CONTINUE
       RETURN
       END
