        INTEGER FUNCTION ICAMAX(N,X,INCX)
        INTEGER N,INCX
        COMPLEX X(INCX,1)
        REAL SMAX
C THIS FUNCTION RETURNS THE INDEX OF THE COMPONENT
C OF X HAVING MAXIMUM MAGNITUDE. ONLY EVERY
C INCXTH COMPONENT OF X IS CONSIDERED
C
        ICAMAX=0
       IF(N.EQ.0) RETURN
C/6S
        IF(N.LT.0) CALL SETERR(13HICAMAX-N.LT.0,13,1,2)
        IF(INCX.LT.1)CALL SETERR(16HICAMAX-INCX.LT.1,16,2,2)
C/7S
C       IF(N.LT.0) CALL SETERR('ICAMAX-N.LT.0',13,1,2)
C       IF(INCX.LT.1)CALL SETERR('ICAMAX-INCX.LT.1',16,2,2)
C/
        SMAX=0.0
        ICAMAX=1
        DO 10 I=1,N
        IF(SMAX.GE.CABS(X(1,I))) GO TO 10
           SMAX=CABS(X(1,I))
           ICAMAX=I
 10     CONTINUE
        RETURN
        END
