        INTEGER FUNCTION IDAMIN(N,X,INCX)
        INTEGER I,N,INCX
        DOUBLE PRECISION X(INCX,1),DMIN
C THIS FUNCTION RETURNS THE INDEX OF THE COMPONENT
C OF X HAVING MINIMUM MAGNITUDE. ONLY EVERY
C INCXTH COMPONENT OF X IS CONSIDERED
C
        IDAMIN=0
        IF(N.EQ.0) RETURN
C/6S
        IF(N.LT.0) CALL SETERR(13HIDAMIN-N.LT.0,13,1,2)
        IF(INCX.LT.1)CALL SETERR(16HIDAMIN-INCX.LT.1,16,2,2)
C/7S
C       IF(N.LT.0) CALL SETERR('IDAMIN-N.LT.0',13,1,2)
C       IF(INCX.LT.1)CALL SETERR('IDAMIN-INCX.LT.1',16,2,2)
C/
        DMIN=DABS(X(1,1))
        IDAMIN=1
        IF(DMIN .EQ. 0.D0) RETURN
        DO 10 I=1,N
        IF(DMIN.LE.DABS(X(1,I))) GO TO 10
           DMIN=DABS(X(1,I))
           IDAMIN=I
           IF(DMIN .EQ. 0.D0) RETURN
 10     CONTINUE
        RETURN
        END
