        INTEGER FUNCTION IDAMAX(N,X,INCX)
        INTEGER N,INCX
        DOUBLE PRECISION X(INCX,1),SMAX
C THIS FUNCTION RETURNS THE INDEX OF THE COMPONENT
C OF X HAVING MAXIMUM MAGNITUDE. ONLY EVERY
C INCXTH COMPONENT OF X IS CONSIDERED
C
        IDAMAX=0
       IF(N.EQ.0) RETURN
C/6S
        IF(N.LT.0) CALL SETERR(13HIDAMAX-N.LT.0,13,1,2)
        IF(INCX.LT.1)CALL SETERR(16HIDAMAX-INCX.LT.1,16,2,2)
C/7S
C       IF(N.LT.0) CALL SETERR('IDAMAX-N.LT.0',13,1,2)
C       IF(INCX.LT.1)CALL SETERR('IDAMAX-INCX.LT.1',16,2,2)
C/
        SMAX=0.D0
        IDAMAX=1
        DO 10 I=1,N
        IF(SMAX.GE.DABS(X(1,I))) GO TO 10
           SMAX=DABS(X(1,I))
           IDAMAX=I
 10     CONTINUE
        RETURN
        END
