        INTEGER FUNCTION IDMIN(N,X,INCX)
        INTEGER I,N,INCX
        DOUBLE PRECISION X(INCX,1),SMIN
C
C THIS FUNCTION RETURNS THE INDEX OF THE SMALLEST (ALGEBRAIC)
C COMPONENT OF X.
C ONLY EVERY INCXTH COMPONENT OF X IS CONSIDERED.
C
        IDMIN=0
        IF(N.EQ.0) RETURN
C/6S
        IF(N.LT.0) CALL SETERR(12HIDMIN-N.LT.0,12,1,2)
        IF(INCX.LT.1)CALL SETERR(15HIDMIN-INCX.LT.1,15,2,2)
C/7S
C       IF(N.LT.0) CALL SETERR('IDMIN-N.LT.0',12,1,2)
C       IF(INCX.LT.1)CALL SETERR('IDMIN-INCX.LT.1',15,2,2)
C/
        SMIN=X(1,1)
        IDMIN=1
        DO 10 I=1,N
        IF(SMIN.LE.X(1,I)) GO TO 10
           SMIN=X(1,I)
           IDMIN=I
 10     CONTINUE
        RETURN
        END
