        INTEGER FUNCTION IIMAX(N,X,INCX)
        INTEGER I,N,INCX
        INTEGER X(INCX,1),IMAX
C
C THIS FUNCTION RETURNS THE INDEX OF THE LARGEST (ALGEBRAIC)
C COMPONENT OF X.
C ONLY EVERY INCXTH COMPONENT OF X IS CONSIDERED.
C
        IIMAX=0
        IF(N.EQ.0) RETURN
C/6S
        IF(N.LT.0) CALL SETERR(12HIIMAX-N.LT.0,12,1,2)
        IF(INCX.LT.1)CALL SETERR(15HIIMAX-INCX.LT.1,15,2,2)
C/7S
C       IF(N.LT.0) CALL SETERR('IIMAX-N.LT.0',12,1,2)
C       IF(INCX.LT.1)CALL SETERR('IIMAX-INCX.LT.1',15,2,2)
C/
        IMAX=X(1,1)
        IIMAX=1
        DO 10 I=1,N
        IF(IMAX.GE.X(1,I)) GO TO 10
           IMAX=X(1,I)
           IIMAX=I
 10     CONTINUE
        RETURN
        END
