        INTEGER FUNCTION ISMIN(N,X,INCX)
        INTEGER I,N,INCX
        REAL X(INCX,1),SMIN
C
C THIS FUNCTION RETURNS THE INDEX OF THE SMALLEST (ALGEBRAIC)
C COMPONENT OF X.
C ONLY EVERY INCXTH COMPONENT OF X IS CONSIDERED.
C
        ISMIN=0
        IF(N.EQ.0) RETURN
C/6S
        IF(N.LT.0) CALL SETERR(12HISMIN-N.LT.0,12,1,2)
        IF(INCX.LT.1)CALL SETERR(15HISMIN-INCX.LT.1,15,2,2)
C/7S
C       IF(N.LT.0) CALL SETERR('ISMIN-N.LT.0',12,1,2)
C       IF(INCX.LT.1)CALL SETERR('ISMIN-INCX.LT.1',15,2,2)
C/
        SMIN=X(1,1)
        ISMIN=1
        DO 10 I=1,N
        IF(SMIN.LE.X(1,I)) GO TO 10
           SMIN=X(1,I)
           ISMIN=I
 10     CONTINUE
        RETURN
        END
