        REAL FUNCTION SAMAX(N,X,INCX)
        INTEGER   N,INCX
        REAL X(INCX,1)
C
C THIS FUNCTIONS RETURNS THE MAGNITUDE OF THE COMPONENT
C OF X HAVING MAXIMUM MAGNITUDE. ONLY EVERY INCXTH
C COMPONENT OF X IS CONSIDERED.
C
        SAMAX=0.0
        IF(N.EQ.0) RETURN
C/6S
        IF(N.LT.0)CALL SETERR(12HSAMAX-N.LT.0,12,1,2)
        IF (INCX.LT.1) CALL SETERR(15HSAMAX-INCX.LT.1,15,2,2)
C/7S
C       IF(N.LT.0)CALL SETERR('SAMAX-N.LT.0',12,1,2)
C       IF (INCX.LT.1) CALL SETERR('SAMAX-INCX.LT.1',15,2,2)
C/
        DO 10 I=1,N
           IF(SAMAX.LT.ABS(X(1,I)))SAMAX=ABS(X(1,I))
 10     CONTINUE
        RETURN
        END
