        REAL FUNCTION SCASUM(N,X,INCX)
C
C THIS FUNCTION RETURNS THE SUM OF THE ABSOLUTE VALUES
C OF THE COMPONENTS OF X. ONLY EVERY INCXTH COMPONENT
C OF X IS CONSIDERED
       COMPLEX X(INCX,1)
       SCASUM=0.0
       IF(N.EQ.0) RETURN
C/6S
       IF (N.LT.0) CALL SETERR(13HSCASUM-N.LT.0,13,1,2)
       IF(INCX.LT.1) CALL SETERR(16HSCASUM-INCX.LT.1,16,2,2)
C/7S
C      IF (N.LT.0) CALL SETERR('SCASUM-N.LT.0',13,1,2)
C      IF(INCX.LT.1) CALL SETERR('SCASUM-INCX.LT.1',16,2,2)
C/
       DO 10 I=1,N
          SCASUM=SCASUM+CABS1(X(1,I))
 10    CONTINUE
       RETURN
       END
